base: &base
  adapter: <%= ENV["DB_PG_ADAPTER"] %>
  pool: 10
  timeout: 160

development:
  adapter: postgresql
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["TEST_DB_PASSWORD"] %>
  prepared_statements: false
  pool: 10
  timeout: 160

production:
  adapter: <%= ENV["DB_PG_ADAPTER"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  prepared_statements: false
  pool: 10
  timeout: 160