name: CI pipeline

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0
      - run: bundle install
      - name: Rubocop
        run: rubocop

      - name: Run security checks
        continue-on-error: true
        run: |
          bundler-audit --update
          brakeman -q -w2
        
      